# Generated by Django 4.1.1 on 2022-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_rename_course_fees_course_course_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Course',
            new_name='course',
        ),
    ]
