# Generated by Django 4.1.1 on 2022-10-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_rename_course_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='std_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_Name',
            new_name='std_name',
        ),
    ]
