# Generated by Django 4.1.1 on 2022-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_remove_teacher_name_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
