# Generated by Django 4.1.1 on 2022-10-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0006_remove_teacher_email_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
