# Generated by Django 4.1.1 on 2022-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
